// The custom map builder's palette: floor and wall styles from the assets (maps/builder/builder.json, generated by
// tools/builder.py in the assets repo). No Phaser here, so React components can use it; the game draws the tiles.

export const BUILDER_FOLDER = "/assets/maps/builder/";

type TilesetInfo = { image: string; columns: number; count: number; margin: number; spacing: number };
export type BuilderStyle = { id: number; name: string };
export type Builder = {
  tilesets: { basechip: TilesetInfo; wallup: TilesetInfo };
  // Style id -> tile index in the basechip tileset
  floors: (BuilderStyle & { tile: number })[];
  // Style id -> the [left, middle, right] tiles of a wall's 2-tile front
  walls: (BuilderStyle & { upper: [number, number, number]; lower: [number, number, number] })[];
  // Wall-Up tile for a wall cell, by which of its 8 neighbours are walls (bits: N NE E SE S SW W NW)
  wallTop: number[];
};

/** What painting with the brush does: lay a floor or wall style, or clear the tile. */
export type PaintTool = { kind: "floor" | "wall"; style: number } | { kind: "erase" };

/** Preview image of a floor or wall style, for the editor's palette. */
export const stylePreviewUrl = (kind: "floor" | "wall", id: number) => `${BUILDER_FOLDER}previews/${kind}-${id}.png`;

/** The palette data (the game loads its own copy through Phaser's loader). */
export async function fetchBuilder(): Promise<Builder> {
  const res = await fetch(`${BUILDER_FOLDER}builder.json`);
  if (!res.ok) throw new Error("Couldn't load the floor and wall styles");
  return res.json();
}
