import { randomUUID } from "node:crypto";
import { unlink } from "node:fs/promises";
import path from "node:path";
import type { Request, Response } from "express";
import client from "@repo/db/client";
import { customMapSchema } from "@repo/protocol";
import { notifySpace } from "../lib/realtime.js";
import { isPng, saveUpload, UPLOADS_DIR, UPLOADS_URL } from "../lib/uploads.js";

// Covers generated by the editor are stored as thumbnails/space-<spaceId>-<random>.png
const THUMBNAIL_FOLDER = "thumbnails";

/** The space if the caller owns it, or sends 404/403 and returns null. */
async function findOwnedSpace(req: Request, res: Response) {
  const userId = req.user?.id;
  const { spaceId } = req.params;
  if (!userId) {
    res.status(401).json({ message: "Unauthorized" });
    return null;
  }
  if (!spaceId) {
    res.status(400).json({ message: "SpaceId param required" });
    return null;
  }

  const space = await client.space.findUnique({
    where: { id: spaceId },
    select: { id: true, creatorId: true, width: true, height: true, customMap: true, thumbnail: true },
  });
  if (!space) {
    res.status(404).json({ message: "Space not found" });
    return null;
  }
  if (space.creatorId !== userId) {
    res.status(403).json({ message: "You do not have permission to modify this space" });
    return null;
  }
  return space;
}

/** Saves the floors and walls of a custom map, then tells everyone in the space. */
export const updateCustomMap = async (req: Request, res: Response) => {
  const parsed = customMapSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ message: "Validation failed" });
  }

  try {
    const space = await findOwnedSpace(req, res);
    if (!space) return;

    if (!space.customMap) {
      return res.status(400).json({ message: "This space doesn't use a custom map" });
    }
    const tiles = space.width * space.height;
    if (parsed.data.floor.length !== tiles || parsed.data.walls.length !== tiles) {
      return res.status(400).json({ message: `The map must have ${tiles} tiles (${space.width}x${space.height})` });
    }

    await client.space.update({ where: { id: space.id }, data: { customMap: parsed.data } });
    notifySpace(space.id, { type: "map-updated", payload: parsed.data });
    return res.status(200).json({ message: "Map saved" });
  } catch (e) {
    console.error(e);
    return res.status(500).json({ message: "Internal Server Error" });
  }
};

/** Replaces the space's cover with a PNG rendered by the editor. */
export const uploadSpaceThumbnail = async (req: Request, res: Response) => {
  try {
    const space = await findOwnedSpace(req, res);
    if (!space) return;

    const file = req.file;
    if (!file) {
      return res.status(400).json({ message: "A file field is required" });
    }
    if (!isPng(file.buffer)) {
      return res.status(400).json({ message: "Only PNG images are accepted" });
    }

    // A new name each time, so browsers don't keep showing a cached cover
    const url = await saveUpload(
      `${THUMBNAIL_FOLDER}/space-${space.id}-${randomUUID().slice(0, 8)}.png`,
      file.buffer
    );
    await client.space.update({ where: { id: space.id }, data: { thumbnail: url } });

    // Remove the previous generated cover (never a map's shared thumbnail)
    const previousPrefix = `${UPLOADS_URL}/${THUMBNAIL_FOLDER}/space-${space.id}-`;
    if (space.thumbnail?.startsWith(previousPrefix)) {
      const previous = path.join(UPLOADS_DIR, THUMBNAIL_FOLDER, path.basename(space.thumbnail));
      unlink(previous).catch(() => {});
    }

    return res.status(200).json({ thumbnail: url });
  } catch (e) {
    console.error(e);
    return res.status(500).json({ message: "Internal Server Error" });
  }
};
